apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodestatuses.ha.example.com
spec:
  group: ha.example.com
  names:
    plural: nodestatuses
    singular: nodestatus
    kind: NodeStatus
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
