apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicespecs.ha.example.com
spec:
  group: ha.example.com
  names:
    plural: servicespecs
    singular: servicespec
    kind: ServiceSpec
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
