apiVersion: v1
kind: Pod
metadata:
  name: object-workergpu-30500
  labels:
    app: object
spec:
  containers:
  - name: object
    image: harbor.pdc.tw/arha/object:breakwater
    readinessProbe:
      httpGet:
        path: /ping
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
    ports:
    - containerPort: 7000
      hostPort: 30500
    resources:
      limits:
        nvidia.com/gpu: 1