apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gpu-util-exporter
  labels:
    release: prometheus-stack  # 注意要跟 Prometheus release 名稱對得上
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - pose
      - gesture
  podMetricsEndpoints:
  - port: gpu-metrics
    path: /metrics
    interval: 5s
