apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pose-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pose-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Pods
    pods:
      metric:
        name: DCGM_FI_DEV_GPU_UTIL
      target:
        type: AverageValue
        averageValue: "30"  # 以 30% GPU 使用率為擴縮目標
